# fileVersion: 0.7
version: "2.2"
services:
  transmission:
    image: linuxserver/transmission
    environment:
      - TZ=Asia/Seoul
      - LC_ALL=C.UTF-8
      - PUID=1000
      - PGID=1000
      - USER=${ID}
      - PASS=${PASS}
    volumes:
      - ${DOWNLOADS}:/downloads
    volumes_from:
      - manager
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
    depends_on:
      - manager
  manager:
    image: istandthon7/torrentscraper
    environment:
      - TZ=Asia/Seoul
      - LC_ALL=C.UTF-8
      - VIDEO=${VIDEO}
      - DOWNLOADS=${DOWNLOADS}
      - ID=${ID}
      - PASS=${PASS}
    volumes:
      - ${VIDEO}:/tm/video
      - torrent_manager:/scraper/config
    ports:
      - ${PORT}:80
    restart: unless-stopped
volumes:
  torrent_manager:
